services:
  - type: web
    name: my-django-app
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: SECRET_KEY
        value: "{{ SECRET_KEY }}"
